#!/usr/bin/env bash
#
# BookFree — one-click Docker deploy.
#
# What this script does on first run:
#   1. Verifies docker + docker compose are installed
#   2. Creates ./data/ if missing (where the SQLite DB and uploads live)
#   3. Generates a strong APP_SECRET into ./.env if missing
#   4. Builds the image (only if the user hasn't pre-built it)
#   5. Starts the stack
#   6. Waits for the health endpoint to come green and prints the URL
#
# Subsequent runs:
#   - Detect that ./.env exists and reuse the secret
#   - `docker compose up -d --build` to pick up source changes
#
# Idempotent. Safe to run repeatedly.

set -euo pipefail

cd "$(dirname "$0")"

# ─── helpers ─────────────────────────────────────────────────────────
red()    { printf '\033[31m%s\033[0m\n' "$*"; }
green()  { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
blue()   { printf '\033[34m%s\033[0m\n' "$*"; }

require() {
    if ! command -v "$1" >/dev/null 2>&1; then
        red "❌ Required command not found: $1"
        echo "   $2"
        exit 1
    fi
}

# ─── prereq checks ───────────────────────────────────────────────────
blue "▶ Checking prerequisites…"
require docker "Install Docker: https://docs.docker.com/get-docker/"

# `docker compose` (plugin) is preferred; fall back to legacy `docker-compose`.
if docker compose version >/dev/null 2>&1; then
    COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE="docker-compose"
    yellow "ℹ Using legacy docker-compose. Recommended: upgrade to the v2 plugin (docker compose)."
else
    red "❌ docker compose plugin not found"
    echo "   Install with: https://docs.docker.com/compose/install/"
    exit 1
fi
green "✓ docker + $COMPOSE found"

# ─── .env: generate APP_SECRET if missing ────────────────────────────
if [[ ! -f .env ]]; then
    blue "▶ Generating .env with a fresh APP_SECRET…"
    # Prefer openssl; fall back to /dev/urandom if not installed. Both
    # produce 32 bytes (64 hex chars) of cryptographically random data.
    if command -v openssl >/dev/null 2>&1; then
        SECRET=$(openssl rand -hex 32)
    else
        SECRET=$(head -c 32 /dev/urandom | xxd -p | tr -d '\n')
    fi
    cat > .env <<EOF
# Generated by docker-quickstart.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT commit this file. DO back it up — losing this secret means
# every encrypted AI provider key in the database becomes unrecoverable.

BOOKFREE_APP_SECRET=$SECRET

# Optional overrides. Uncomment as needed.
# BOOKFREE_LOG_LEVEL=info
# BOOKFREE_MAX_UPLOAD_SIZE_MB=200
# BOOKFREE_ALLOW_REGISTRATION=1
# TZ=Asia/Shanghai
EOF
    chmod 600 .env
    green "✓ Wrote .env (chmod 600). Back this file up."
else
    green "✓ .env already exists — keeping existing APP_SECRET"
fi

# ─── data dir ────────────────────────────────────────────────────────
mkdir -p data/storage
green "✓ ./data/ ready (SQLite + uploads will live here)"

# ─── build + start ───────────────────────────────────────────────────
blue "▶ Building image (this can take 1-3 minutes on first run)…"
$COMPOSE --env-file .env build

blue "▶ Starting container…"
$COMPOSE --env-file .env up -d

# ─── wait for health ─────────────────────────────────────────────────
blue "▶ Waiting for /api/health to come green…"
PORT=$(grep -E '^\s*-\s*"127\.0\.0\.1:[0-9]+:8788"' docker-compose.yml \
       | grep -oE '127\.0\.0\.1:[0-9]+' | cut -d: -f2 | head -1)
PORT=${PORT:-8788}
URL="http://127.0.0.1:$PORT/api/health"

# Poll up to 30 seconds. Most starts complete in ~3.
for i in $(seq 1 30); do
    if curl -fsS "$URL" >/dev/null 2>&1; then
        break
    fi
    sleep 1
done

if curl -fsS "$URL" >/dev/null 2>&1; then
    green "✓ BookFree is up: http://127.0.0.1:$PORT"
    echo
    echo "Quick links:"
    echo "  • Web UI:     http://127.0.0.1:$PORT"
    echo "  • Health:     http://127.0.0.1:$PORT/api/health"
    echo
    echo "Useful commands:"
    echo "  $COMPOSE logs -f          # tail logs"
    echo "  $COMPOSE down             # stop"
    echo "  $COMPOSE up -d --build    # rebuild + restart after source changes"
    echo "  $COMPOSE exec bookfree /app/bookfree-server make-admin you@example.com"
    echo
    yellow "⚠ Self-serve registration is DISABLED by default in production."
    yellow "  Recommended: temporarily enable, register your account, promote to admin, then disable."
    yellow "  Quick recipe:"
    yellow "    docker compose --env-file .env exec -e BOOKFREE_ALLOW_REGISTRATION=1 \\"
    yellow "      bookfree /app/bookfree-server make-admin you@example.com"
    yellow "  Or set BOOKFREE_ALLOW_REGISTRATION=1 in .env permanently for single-user deployments."
else
    red "❌ Container started but /api/health didn't respond in 30s"
    echo "   Check logs:  $COMPOSE logs --tail=50"
    exit 1
fi
